# Assets Manifest

# This file lists all the assets used in the game, including fonts, textures, sound buffers, and music.
# Each asset is defined with a unique identifier and its corresponding file path.
# You can try out different assets by changing the paths below, but do not change the id's.

# --- Fonts ---
# Must be .ttf files
[[fonts]]
id = "MainFont"
path = "resources/fonts/CaesarDressing-Regular.ttf"

[[fonts]]
id = "ScoreFont"
path = "resources/fonts/Micro5-Regular.ttf"

# --- Textures ---
[[textures]]

# --- SoundBuffers ---
[[soundbuffers]]
id = "BrickHit"
path = "resources/sounds/brickHit.wav"

[[soundbuffers]]
id = "PaddleHit"
path = "resources/sounds/paddleHit.wav"

[[soundbuffers]]
id = "WallHit"
path = "resources/sounds/wallHit.wav"

[[soundbuffers]]
id = "NormBrickBreak"
path = "resources/sounds/normalBrickBreak.wav"

[[soundbuffers]]
id = "GoldBrickBreak"
path = "resources/sounds/goldBrickBreak.wav"

[[soundbuffers]]
id = "StrongBrickBreak"
path = "resources/sounds/strongBrickBreak.wav"

# --- Music ---
# .ogg files are preferred, but .mp3 files should also work
[[musics]]
id = "MainSong"
path = "resources/music/VideoGameAm.ogg"