# Assets Manifest

# This file lists all the assets used in the game, including fonts, textures, sound buffers, and music.
# Each asset is defined with a unique identifier and its corresponding file path.
# You can try out different assets by changing the paths below, but do not change the id's.

# --- Fonts ---
# Must be .ttf files
[[fonts]]
id = "MainFont"
path = "resources/fonts/CaesarDressing-Regular.ttf"

[[fonts]]
id = "ScoreFont"
path = "resources/fonts/Micro5-Regular.ttf"

# --- Textures ---
# GUI textures
[[textures]]
id = "Cursor"
path = "resources/GUI/cursor.png"

[[textures]]
id = "RadioBackground"
path = "resources/GUI/radioBackground.png"

[[textures]]
id = "RadioCheckmark"
path = "resources/GUI/radioCheckmark.png"

[[textures]]
id = "RadioHover"
path = "resources/GUI/radioHover.png"

[[textures]]
id = "BoxBackground"
path = "resources/GUI/boxBackground.png"

[[textures]]
id = "ButtonRedX"
path = "resources/GUI/buttonS1RedX.png"

[[textures]]
id = "ButtonArrow"
path = "resources/GUI/buttonS1Arrow.png"

[[textures]]
id = "ButtonBackground"
path = "resources/GUI/buttonS1Background.png"

# --- SoundBuffers ---
[[soundbuffers]]
id = "BrickHit"
path = "resources/sounds/brickHit.wav"

[[soundbuffers]]
id = "PaddleHit"
path = "resources/sounds/paddleHit.wav"

[[soundbuffers]]
id = "WallHit"
path = "resources/sounds/wallHit.wav"

[[soundbuffers]]
id = "NormBrickBreak"
path = "resources/sounds/normalBrickBreak.wav"

[[soundbuffers]]
id = "GoldBrickBreak"
path = "resources/sounds/goldBrickBreak.wav"

[[soundbuffers]]
id = "StrongBrickBreak"
path = "resources/sounds/strongBrickBreak.wav"

# --- Music ---
# .ogg files are preferred, but .mp3 files should also work
[[musics]]
id = "MainSong"
path = "resources/musics/swung.ogg"
