# --- Fonts ---
[[fonts]]
id = "MainFont"
path = "resources/fonts/CaesarDressing-Regular.ttf"

# --- Textures ---
[[textures]]

# --- SoundBuffers ---
[[soundbuffers]]

# --- Music ---
[[musics]]
id = "MainSong"
path = "resources/music/VideoGameAm.ogg"