# Bricks Cofiguration File

# scoreValue and healthMax must be positive numbers.
# RGB values must be between 0 and 255.

[normal] # Code 'N' in Levels
scoreValue = 5 
healthMax = 1 
normalRGB = [66, 170, 139] 

[strong] # Code 'S' in Levels
scoreValue = 10 
healthMax = 2 
strongRGB = [87, 117, 144] 

[strongDamaged] # Just for changing the color of strong when hit
strongDamagedRGB = [76, 144, 142] 

[gold] # Code 'G' in Levels
scoreValue = 20 
healthMax = 1 
goldRGB = [249, 199, 79] 

[custom_1] # Code 'X' in Levels
scoreValue = 67 
healthMax = 0 
custom_1RGB = [50, 250, 250] 

[custom_2] # Code 'Y' in Levels
scoreValue = 100 
healthMax = 3 
custom_2RGB = [150, 10, 155] 