# Levels Configuration File

############################################
# N = normal brick
# G = gold brick
# S = strong brick
# X = custom_1 brick
# Y = custom_2 brick
# . = empty space

# 120 x 40 bricks = 10 bricks per row
# 60 x 20 bricks = 19 bricks per row
# I haven't tried out different brick sizes besides these two.
# You can play around with it and if you encounter bugs let me know :)
# Make sure the layout rows are all the same length for each level!
#     e.g. levels with 120x40 bricks should have rows of length 10, 
#          60x20 bricks should have rows of length 19.

# brickWidth and brickHeight are in pixels, must be positive numbers and 
# should end in .0

# descentSpeed is how fast the bricks descend in pixels per seconds
# values must be a positive float (0.0 to 9000.0)
############################################

# The total number of levels
# Don't forget to update this if you add/remove levels!
totalLevels = 7

# If you add levels, the section MUST be named level_NUMBER
[level_1]
brickWidth = 120.0
brickHeight = 40.0
descentSpeed = 18.0
layout = [
    "..N....N..", # Don't forget the comma if there is more than one row!
    "...N..N...",
    "....NN...."
]

[level_2]
brickWidth = 120.0
brickHeight = 40.0
descentSpeed = 15.0
layout = [
    "N...SS...N",
    ".G......G.",
    "N........N"  # But do NOT add a comma on the last row
]

[level_3]
brickWidth = 120.0
brickHeight = 40.0
descentSpeed = 10.0
layout = [
    "N........N",
    "N.X....X.N",
    "N..Y..Y..N",
    "N........N",
    "....GG...."  # But do NOT add a comma on the last row
]

[level_4]
brickWidth = 60.0
brickHeight = 20.0
descentSpeed = 12.0
layout = [
    "G........G........G", 
    "........Y.Y........",
    ".......YY.YY.......", # Look at those commas!
    "........Y.Y........",
    "..................."
]

[level_5]
brickWidth = 60.0
brickHeight = 20.0
descentSpeed = 5.0
layout = [
    "X...XYYYYX...XYYYYY",
    "XX..XY..YXX..X..Y..",
    "X.X.XYYYYX.X.X..Y..",
    "X..XXY..YX..XX..Y..",
    "X...XY..YX...X..Y..",
    "..................." # <-- look at there NOT being a comma!
]

[level_6]
brickWidth = 60.0
brickHeight = 20.0
descentSpeed = 5.0
layout = [
    "NNN....G...G....XXX",
    "NSN...G.....G...XYX",
    "NNN..G.......G..XXX",
    "...NNNNNNNNNNNNN...",
    "..................."
]

[level_7]
brickWidth = 60.0
brickHeight = 20.0
descentSpeed = 5.0
layout = [
    ".......GGGG........",
    ".....GG....GG......",
    "....G..Y..Y..G.....",
    "....G.X....X.G.....",
    "....G..XXXX..G.....",
    ".....GG....GG......",
    ".......GGGG........"
]
