# Player (Paddle) Configuration File

# Speed, width and height must be positive numbers. They are in pixels.
# RGB values must be between 0 and 255.

[player]
movementSpeed = 400.0 
paddleWidth = 120.0
paddleHeight = 20.0
paddleRGB = [250, 250, 250]