[player]
movementSpeed = 400.0 # Suggested range: 250 - 550
paddleWidth = 120.0 # Must be a positive number
paddleHeight = 20.0 # Must be a positive number
paddleRGB = [250, 250, 250] # MUST BE between 0, 0 ,0 and 255, 255, 255